version: 2
updates:
  - package-ecosystem: npm
    directory: /
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps(node): "
    groups:
      tauri:
        patterns:
          - "@tauri*"
        update-types:
          - "minor"
          - "patch"
      dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@tauri*"
      devDependencies: 
        dependency-type: "development"
        exclude-patterns:
          - "@tauri*"
  - package-ecosystem: docker
    directory: /docker
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps(docker): "

  - package-ecosystem: github-actions
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(actions): "
    groups:
      docker:
        patterns:
          - "docker*"
      gcp:
        patterns:
          - "google-github-actions*"
      others:
        patterns:
          - "*"
